name: 'Setup Tools'
description: 'Install and cache kubectl and helm binaries with SHA256 verification'

inputs:
  kubectl-version:
    description: 'kubectl version (e.g., v1.31.0)'
    required: true
  helm-version:
    description: 'Helm version (e.g., v3.16.0)'
    required: false
    default: 'v3.16.0'
  architecture:
    description: 'Target architecture (arm64 or amd64)'
    required: false
    default: 'arm64'
  install-helm:
    description: 'Whether to install helm (default: true)'
    required: false
    default: 'true'

outputs:
  kubectl-path:
    description: 'Path to kubectl binary'
    value: /usr/local/bin/kubectl
  helm-path:
    description: 'Path to helm binary'
    value: /usr/local/bin/helm

runs:
  using: 'composite'
  steps:
    # ===== Input validation =====
    - name: Validate inputs
      shell: bash
      run: |
        set -euo pipefail

        # Validate kubectl-version format (vX.Y.Z)
        if ! [[ "${{ inputs.kubectl-version }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "ERROR: Invalid kubectl-version format. Expected vX.Y.Z (e.g., v1.31.0)"
          echo "Received: '${{ inputs.kubectl-version }}'"
          exit 1
        fi

        # Validate helm-version format (vX.Y.Z) if helm will be installed
        if [[ "${{ inputs.install-helm }}" == "true" ]]; then
          if ! [[ "${{ inputs.helm-version }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "ERROR: Invalid helm-version format. Expected vX.Y.Z (e.g., v3.16.0)"
            echo "Received: '${{ inputs.helm-version }}'"
            exit 1
          fi
        fi

        # Validate architecture
        if ! [[ "${{ inputs.architecture }}" =~ ^(arm64|amd64)$ ]]; then
          echo "ERROR: Invalid architecture. Must be 'arm64' or 'amd64'"
          echo "Received: '${{ inputs.architecture }}'"
          exit 1
        fi

        echo "Input validation passed"

    # ===== kubectl installation =====
    - name: Create kubectl cache directory
      shell: bash
      run: mkdir -p "${{ runner.temp }}/kubectl-cache"

    - name: Cache kubectl
      id: cache-kubectl
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: ${{ runner.temp }}/kubectl-cache/kubectl
        key: kubectl-linux-${{ inputs.architecture }}-${{ inputs.kubectl-version }}

    - name: Install kubectl
      if: steps.cache-kubectl.outputs.cache-hit != 'true'
      shell: bash
      run: |
        set -euo pipefail
        echo "Installing kubectl ${{ inputs.kubectl-version }} for ${{ inputs.architecture }}..."

        # Download kubectl and checksum
        curl --connect-timeout 10 --max-time 60 -fLO \
          "https://dl.k8s.io/release/${{ inputs.kubectl-version }}/bin/linux/${{ inputs.architecture }}/kubectl"
        curl --connect-timeout 10 --max-time 30 -fLO \
          "https://dl.k8s.io/release/${{ inputs.kubectl-version }}/bin/linux/${{ inputs.architecture }}/kubectl.sha256"

        # Verify checksum
        echo "Verifying kubectl checksum..."
        EXPECTED_HASH=$(cat kubectl.sha256)
        echo "${EXPECTED_HASH}  kubectl" | sha256sum --check --strict
        echo "Checksum verification passed"

        # Cache the binary
        chmod +x kubectl
        mv kubectl "${{ runner.temp }}/kubectl-cache/kubectl"
        rm kubectl.sha256

        echo "kubectl ${{ inputs.kubectl-version }} downloaded successfully"

    - name: Install kubectl to PATH
      shell: bash
      run: |
        sudo cp "${{ runner.temp }}/kubectl-cache/kubectl" /usr/local/bin/kubectl
        sudo chmod +x /usr/local/bin/kubectl
        echo "kubectl installed to /usr/local/bin/"

    - name: Verify kubectl
      shell: bash
      run: |
        echo "kubectl version: $(kubectl version --client --short 2>/dev/null || kubectl version --client)"

    # ===== Helm installation =====
    - name: Create helm cache directory
      if: inputs.install-helm == 'true'
      shell: bash
      run: mkdir -p "${{ runner.temp }}/helm-cache"

    - name: Cache helm
      if: inputs.install-helm == 'true'
      id: cache-helm
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: ${{ runner.temp }}/helm-cache/helm
        key: helm-linux-${{ inputs.architecture }}-${{ inputs.helm-version }}

    - name: Install helm
      if: inputs.install-helm == 'true' && steps.cache-helm.outputs.cache-hit != 'true'
      shell: bash
      run: |
        set -euo pipefail
        echo "Installing helm ${{ inputs.helm-version }} for ${{ inputs.architecture }}..."

        # Download helm tarball and checksum
        HELM_TARBALL="helm-${{ inputs.helm-version }}-linux-${{ inputs.architecture }}.tar.gz"
        curl --connect-timeout 10 --max-time 180 -fLO \
          "https://get.helm.sh/${HELM_TARBALL}"
        curl --connect-timeout 10 --max-time 30 -fLO \
          "https://get.helm.sh/${HELM_TARBALL}.sha256sum"

        # Verify checksum (parse hash from file to handle format variations)
        echo "Verifying helm checksum..."
        EXPECTED_HASH=$(awk '{print $1}' "${HELM_TARBALL}.sha256sum")
        echo "${EXPECTED_HASH}  ${HELM_TARBALL}" | sha256sum --check --strict
        echo "Checksum verification passed"

        # Extract and cache the binary
        tar -zxf "$HELM_TARBALL" "linux-${{ inputs.architecture }}/helm"
        chmod +x "linux-${{ inputs.architecture }}/helm"
        mv "linux-${{ inputs.architecture }}/helm" "${{ runner.temp }}/helm-cache/helm"
        rm -rf "$HELM_TARBALL" "${HELM_TARBALL}.sha256sum" "linux-${{ inputs.architecture }}"

        echo "helm ${{ inputs.helm-version }} downloaded successfully"

    - name: Install helm to PATH
      if: inputs.install-helm == 'true'
      shell: bash
      run: |
        sudo cp "${{ runner.temp }}/helm-cache/helm" /usr/local/bin/helm
        sudo chmod +x /usr/local/bin/helm
        echo "helm installed to /usr/local/bin/"

    - name: Verify helm
      if: inputs.install-helm == 'true'
      shell: bash
      run: |
        echo "helm version: $(helm version --short)"
